---
title: "EDA"
author: "Zachariah Freitas"
date: "`r Sys.Date()`"
output: rmarkdown::github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
  fig.path = "README_figs/README-",
  echo = TRUE)
library(zoo)
library(tidyverse)
library(fpp2) # Plot and Forecast Data
set.seed(506)
library(readxl)
library(feasts)
library(tsibble)
# library(tsibbledata)
library(dplyr)
library(ggplot2)
library(lubridate)

df <- read_excel("Sales_Forecasting.xlsx", sheet = "Sales_Data")

# Convert Quarter character to date
df$date <- as.Date(df$svc_agreement_activation_date)
```

## EDA


```{r}

# Create Time Series Object
myts <- ts(df$activation_count, 
           start = c(2021, as.numeric(format(df$date[1], "%j"))),
           frequency = 365)


autoplot(myts) +
  xlab("Date") + 
  ylab("Activations") +
  ggtitle("Forecasts for daily activations") +
  theme_minimal() +
  guides(colour=guide_legend(title="Forecast"))



```


```{r}

temp <- df %>% 
  mutate(svc_agreement_activation_date = as.Date(svc_agreement_activation_date)) %>% 
  as_tsibble(., index = svc_agreement_activation_date)

temp %>% 
  gg_season(activation_count, period = "week") +
  theme(legend.position = "right") +
  labs(y="Activations", x="Day of Week", title="Activation Counts by Day")
```




```{r models}
library(forecast)

# Split Data
train <- window(myts, end = c(2022, 273)) #273 orig 300
valid <- window(myts, start = c(2022, 274)) # October of 2022

# Set Forecast periods
h <- length(myts) - length(train)

############
# Naïve Models
mean_fit <- meanf(train,h=h) # Naïve: Mean
naive_fit <- naive(train,h=h,level = 95) # Naïve: Last Value
drift_fit <- rwf(train,h=h,drift=TRUE) # Naïve: Drift Method
snaive_fit <- snaive(train,h=h) # Naïve: Seasonal Naïve

#############
# Train Models
# Trend + Seasonal Model
ST <- forecast::forecast(forecast::tslm(train ~ trend + season),h=h)

# Exponential Model
EXP <- forecast::forecast(forecast::tslm(train ~ trend + season, lambda = 0),h=h)

#TBats
TBATS <- forecast::forecast(tbats(train, biasadj=TRUE), h=h)




# Neural networks

# non-seasonal lags
# ar(p)
# p = 3

# seasonal Lags
# P = 1

# size = (p + P + 1)/2  rounded to nearest integer
# 3 + 1 + 1 = 5 / 2 = 3
# This is a heuristic



# NNAR - Autofit neural network
NNAR.AF <- forecast::forecast(nnetar(train), h=h)#, lambda=0)


# NNAR - neural network
NNAR <- forecast::forecast(nnetar(train, p = 14, size = 8), h=h)#, lambda=0)



#STL
# STL <- stlf(train, lambda=0, h=h, biasadj=TRUE)
# Auto ARIMA
ARIMA <- forecast::forecast(auto.arima(train, lambda=0, biasadj=TRUE),h=h)
# ETS
ETS <- forecast::forecast(ets(train), h=h)

DHOLT <- holt(train, damped=TRUE, phi = 0.9, h=h)


# Dynamic harmonic regression
k = 1
fit <- auto.arima(train, xreg = fourier(train, K = k), seasonal = FALSE, lambda = 0)
model <- forecast::forecast(fit, xreg=fourier(train, K=k, h=h))

Combination <- (EXP[["mean"]] + 
                  ARIMA[["mean"]] +
                  ST[["mean"]] + 
                  NNAR[["mean"]] + 
                  TBATS[["mean"]])/5

```


```{r Model Plots}

# Plot Results
autoplot(window(myts, start=c(2022, 250))) +
  autolayer(mean_fit, series="Naïve: Mean", PI=FALSE) +
  # autolayer(drift_fit, series="Naïve: Drift Method", PI=FALSE) +
  # autolayer(snaive_fit, series="Naïve: Seasonal Naïve", PI=FALSE) +
  # autolayer(naive_fit, series="Naïve: Last Value", PI=FALSE) +
  # autolayer(ST, series="Seasonal Trend", PI=FALSE) +
  autolayer(EXP, series="Exponential", PI=FALSE) +
  # autolayer(SPLINE, series="Spline", PI=FALSE) +
  # autolayer(ARIMA, series="ARIMA", PI=FALSE) +
  autolayer(TBATS, series="TBATS", PI=FALSE) +
  autolayer(NNAR.AF, series="NNAR Auto", PI=FALSE) +
  autolayer(NNAR, series="NNAR", PI=FALSE) +
  # autolayer(ETS, series="ETS", PI=FALSE) +
  autolayer(DHOLT, series="Damped Holt's method", PI=FALSE) +
  autolayer(model, series="Dynamic harmonic regression", PI=FALSE) +
  autolayer(Combination, series="Combination") +
  xlab("Date") + 
  ylab("Activations") +
  ggtitle("Forecasts for daily activations") +
  theme_minimal() +
  guides(colour=guide_legend(title="Forecast"))
```

## Including Plots
```{r results}
window_df <- window(myts, start=2021)
print(strrep("#", 80))
print("Naïve: Mean")
forecast::accuracy(mean_fit, valid)
print(strrep("#", 80))
print("Naïve: Last Value")
forecast::accuracy(naive_fit, valid)
print(strrep("#", 80))
print("Naïve: Drift Method")
forecast::accuracy(drift_fit, valid)
print(strrep("#", 80))
print("Naïve: Seasonal Naïve")
forecast::accuracy(snaive_fit, valid)
print(strrep("#", 80))
print("Seasonal Trend")
forecast::accuracy(ST, valid)
print(strrep("#", 80))
print("Exponential")
forecast::accuracy(EXP, valid)
print(strrep("#", 80))
# print("Spline")
# accuracy(spine_fit, valid)
print(strrep("#", 80))
print("Auto Neural Network")
forecast::accuracy(NNAR.AF, valid)

print(strrep("#", 80))
print("Neural Network")
forecast::accuracy(NNAR, valid)
    
    
print(strrep("#", 80))
print("ARIMA")
forecast::accuracy(ARIMA, valid)
print(strrep("#", 80))
print("ETS")
forecast::accuracy(ETS, valid)


```

You can also embed plots, for example:

```{r RMSE}
c(
  `Naïve: Mean`= forecast::accuracy(mean_fit, valid)["Test set","RMSE"],
  `Naïve: Last Value`= forecast::accuracy(naive_fit, valid)["Test set","RMSE"],
  `Naïve: Drift Method`= forecast::accuracy(drift_fit, valid)["Test set","RMSE"],
  `Naïve: Seasonal Naïve`= forecast::accuracy(snaive_fit, valid)["Test set","RMSE"],
  DHR = forecast::accuracy(model, valid)["Test set","RMSE"],
  ETS = forecast::accuracy(ETS, valid)["Test set","RMSE"],
  ARIMA = forecast::accuracy(ARIMA, valid)["Test set","RMSE"],
  ST = forecast::accuracy(ST, valid)["Test set","RMSE"],
  NNAR.AF = forecast::accuracy(NNAR.AF, valid)["Test set","RMSE"],
  NNAR = forecast::accuracy(NNAR, valid)["Test set","RMSE"],
  EXP = forecast::accuracy(EXP, valid)["Test set","RMSE"],
  TBATS = forecast::accuracy(TBATS, valid)["Test set","RMSE"],
  Combination = forecast::accuracy(Combination, valid)["Test set","RMSE"])

```


